@startuml

left to right direction

skinparam packageStyle rectangle

actor user



rectangle Gateway {
  user --> (domain): [2a] subscribe

}

note bottom
  Subscription
  requests are
  distributed
  round robin
endnote


rectangle "Backend API" {
  component app_instance_01
  component app_instance_02
  component app_instance_n

  (domain) --> app_instance_02: [2b] subscribe

}



rectangle "Event Streams" {
component MessageBroker

app_instance_01 --> MessageBroker: [1] subscribe
app_instance_02 --> MessageBroker: [1] subscribe
app_instance_n --> MessageBroker: [1] subscribe

note bottom
  Messages are distributed
  round robin
endnote

component EventSource

(EventSource) -up-> MessageBroker: [3] Event (User)
MessageBroker --> app_instance_n: [3] Event ( User )

}

app_instance_n -up-> (?)
note bottom
  app_instance_n does not
  hold the open connection
endnote

@enduml