@startuml

actor User

group Init STOMP over Websocket Session

User -> nginx: CONNECT
nginx -> WebsocketEventListenerService: CONNECT
WebsocketEventListenerService --> nginx: CONNECTED
WebsocketEventListenerService --> NotificationsDispatcherService: sessionConnected()
NotificationsDispatcherService --> Hazelcast: addMessageListener(this)
nginx -> User: CONNECTED
User -> nginx: SUBSCRIBE user queue
nginx -> WebsocketEventListenerService: SUBSCRIBE user queue

end

box "Backend" #LightBlue
	participant WebsocketEventListenerService
	participant NotificationsDispatcherService
	participant Hazelcast
  participant NotificationsListenerService
end box

group Receive Notification from Kafka

Kafka -> NotificationsListenerService: UserNotification
NotificationsListenerService -> NotificationsDispatcherService: UserNotification
NotificationsDispatcherService -> Hazelcast: Publish(UserNotification)
Hazelcast -> NotificationsDispatcherService: UserNotification
NotificationsDispatcherService -> WebsocketEventListenerService: UserNotification
WebsocketEventListenerService -> nginx: UserNotification
nginx -> User: UserNotification

end


@enduml